---
- name: Create inventory and save vars
  hosts: localhost
  become_user: root
  gather_facts: true
  # vars:
  #   inventory_name: "{{ awx_inventory_name }}"
  #   group_name: "{{ awx_group_name }}"
  #   host_name: "{{ awx_host_name }}"
  #   user_name: "{{ user_names }}"
  #   user_group: "{{ user_groups }}"
  tasks:
    - name: Print the available groups
      getent:
        database: group
      register: out

   
    - name: Fetch available users
      getent:
        database: passwd
      register: users_data

    - name: create user
      user:
        name: "{{ item }}"

        home: '/home/elp'
        state: present
      ignore_errors: true
      register: user_res
      loop: "{{ user_names.split(\n) }}"
      when:
        - '"{{ item }}" not in ansible_facts.getent_passwd'

    - name: setting the fact for user details
      set_fact:
        users_info: "{{ user_res }}"

    - name: Checking the directories before creation
      ansible.builtin.stat:
        path: "{{ path_file }}"
      register: directory_res


    

    
